language: php
php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - hhvm
env: PHPV=0
matrix:
  include:
    - php: 5.2
      dist: precise
      env: PHPV=52
    - php: 5.3
      dist: precise
before_script: |
  if [ "$PHPV" -ne 52 ]; then
    composer install
  else
    export X="$HOME/.idiorm/bin"
    mkdir -p "$X"
    curl -sSfL https://phar.phpunit.de/phpunit-4.phar -o "$X/phpunit"
    chmod +x "$X/phpunit"
  fi
script: |
  if [ "$PHPV" -ne 52 ]; then
    XZ="composer run-script test --"
  else
    XZ="$X/phpunit"
  fi
  $XZ --colors --coverage-text
